### ISSUE TITLE
HostWrapper constructor is not stateless

### ISSUE THREAD

**Issue by Glutexo** [RedHatInsights/insights-host-inventory#149]
Never use a mutable object as a function argument default value! The [_HostWrapper_](https://github.com/RedHatInsights/insights-host-inventory/blob/47adfba7918c48c0f975e15c7f1488ad188ee7f2/app/utils.py#L4) [constructor](https://github.com/RedHatInsights/insights-host-inventory/blob/47adfba7918c48c0f975e15c7f1488ad188ee7f2/app/utils.py#L5) does this and it results in unexpected behavior. See:

```python
>>> type(HostWrapper().insights_id)
<class 'NoneType'>
>>> HostWrapper().insights_id = "337a287f-e2d9-4692-856d-19efc548a04d"
>>> HostWrapper().insights_id
'337a287f-e2d9-4692-856d-19efc548a04d'
```

Why this happens? Because the default [constructor](https://github.com/RedHatInsights/insights-host-inventory/blob/47adfba7918c48c0f975e15c7f1488ad188ee7f2/app/utils.py#L5) argument (_data_) is always **the same object**. This happens:

1. The first instance [receives](https://github.com/RedHatInsights/insights-host-inventory/blob/47adfba7918c48c0f975e15c7f1488ad188ee7f2/app/utils.py#L5) a default argument – a dictionary.
2. This dictionary is stored in an instance variable (__data).
3. The _"insights_id"_ value is [stored](https://github.com/RedHatInsights/insights-host-inventory/blob/47adfba7918c48c0f975e15c7f1488ad188ee7f2/app/utils.py#L23) as a new key into the ___data_ dictionary.
4. The second instance [receives](https://github.com/RedHatInsights/insights-host-inventory/blob/47adfba7918c48c0f975e15c7f1488ad188ee7f2/app/utils.py#L5) **the same dictionary** as a default value. This dictionary already has the _"insights_id"_ key from the assignment to the first instance.

If you create many hosts without passing the _data_ argument to the [constructor](https://github.com/RedHatInsights/insights-host-inventory/blob/47adfba7918c48c0f975e15c7f1488ad188ee7f2/app/utils.py#L5). All the instances will share the same ___data_ attribute.

**Comment by dehort** [comment]
@Glutexo gotcha.  Thank you for the python lesson here.  I did not realize it behaved like that.  Lesson learned.  Take a look at PR#152 and let me know what you think.

**Comment by dehort** [comment]
Fix is merged.  Closing.
