### ISSUE TITLE
Host 'id' field - UUID or Integer?

### ISSUE THREAD

**Issue by PaulWay** [RedHatInsights/insights-host-inventory#18]
In the model definition of the id field:
`id = db.Column(db.Integer, primary_key=True)`
In the migration definition of the id field:
`Column("id", UUID(), primary_key=True)`
Is it an integer or a UUID?

**Comment by PaulWay** [comment]
This is fixed by https://github.com/RedHatInsights/insights-host-inventory/pull/19

**Comment by Glutexo** [comment]
#19 is merged. The primary key is now UUID. Closing.
