### ISSUE TITLE
Host lists should be paginated correctly

### ISSUE THREAD

**Issue by PaulWay** [RedHatInsights/insights-host-inventory#29]
The current (attempt at) pagination structure returned by `getHostList` and `getHostById` is not defined in the Swagger interface description.  It is also not implemented as yet.

The usual pagination data in a paginated view includes:
* The current page length
* The current page number OR the offset from the first item
* The total number of items in the requested set (where possible)
* The values as a list
* Links to the 'next' and 'previous' pages, if available.

It should also be possible to request a particular page of items or the offset from the first item, and the number of items per page.

**Comment by PaulWay** [comment]
Tracked in https://projects.engineering.redhat.com/browse/RHIPLAT1-637

**Comment by dehort** [comment]
Fix committed to master.
