### ISSUE TITLE
Wrong format of `x-rh-identity` in auth/__init__.py

### ISSUE THREAD

**Issue by karelhala** [RedHatInsights/insights-host-inventory#40]
Identity header should have `identity` key and then should follow user informations.

### Example:
* Curent
`{account_number: '1111', org_id: '11111c1'}` in BASE64: `eyJhY2NvdW50X251bWJlciI6IjExMTEiLCJvcmdfaWQiOiIxMTExMWMxIn0=`
* Expected
`{identity: {account_number: '1111', org_id: '11111c1'}}` in BASE64 `eyJpZGVudGl0eSI6eyJhY2NvdW50X251bWJlciI6IjExMTEiLCJvcmdfaWQiOiIxMTExMWMxIn19`

**Comment by karelhala** [comment]
ping @Glutexo you might be interested

**Comment by Glutexo** [comment]
So that’s the reason why this didn’t work for Alberto. This should be an easy fix in the identity module.
