### ISSUE TITLE
Namespace KeyError creates an internal server error

### ISSUE THREAD

**Issue by myersCody** [RedHatInsights/insights-host-inventory#56]
When posting to the `\hosts` endpoint, if the body's `facts` dictionary does not contain the key `namespace` an internal server error will be raised.  

**Logs:** 

> File "/insights-host-inventory/app/auth/__init__.py", line 46, in _wrapper
>     return view_func(*args, **kwargs)
>   File "/insights-host-inventory/api/host.py", line 35, in addHost
>     input_host = Host.from_json(host)
>   File "/insights-host-inventory/app/models.py", line 93, in from_json
>     convert_json_facts_to_dict(d.get("facts", [])),
>   File "/insights-host-inventory/app/models.py", line 41, in convert_json_facts_to_dict
>     if fact["namespace"] in fact_dict:
> KeyError: 'namespace'

Potential Fix: 

File: app/models.py
```
def convert_json_facts_to_dict(fact_list):
    fact_dict = {}
    for fact in fact_list:
        if fact.get("namespace", False):
            if fact["namespace"] in fact_dict:
                fact_dict[fact["namespace"]].update(fact["facts"])
            else:
                fact_dict[fact["namespace"]] = fact["facts"]
        else: 
            # 400 Error
    return fact_dict
```

**Comment by dehort** [comment]
I'm not sure why the validation checking in Connexion did not catch this.  I added some code to explicitly check for it and throw an exception.  I also added an error handler to flask/connexion that will convert the exception into http error page.

@myersCody thank you for the bug report.  Let me know if you see any issues with this now.
