### ISSUE TITLE
Remove a redundant logger from api.host

### ISSUE THREAD

**Issue by Glutexo** [RedHatInsights/insights-host-inventory#91]
There is an unused [_logger_](https://github.com/RedHatInsights/insights-host-inventory/blob/e56670337bb84a9bc1368e8f0a8018223c051faf/api/host.py#L15) in the [_api.host_](https://github.com/RedHatInsights/insights-host-inventory/blob/e56670337bb84a9bc1368e8f0a8018223c051faf/api/host.py) module. It’s actually not used anywhere since the app uses `current_app.logger` instead. Remove this ghost variable.

**Comment by dehort** [comment]
I noticed this while working on the insights_id dedup change.  Its fixed now.

**Comment by Glutexo** [comment]
Thanks! Closing.
