### ISSUE TITLE
Providing inventory_id in different format results in 500ISE

### ISSUE THREAD

**Issue by jiridostal** [RedHatInsights/insights-host-inventory#92]
When calling /hosts/$ID, $ID needs to be in specific format of inventory_id ie. 3895b09f-1998-448e-bad3-d251e98316de. If it's not, API returns 500 and not empty list which should be the correct behavior I suppose.

**Comment by Glutexo** [comment]
Pinning this as this looks like a bug bug to me.

**Comment by Glutexo** [comment]
This bug is still present. Created a new ticket for this. 
https://projects.engineering.redhat.com/browse/RHCLOUD-350

**Comment by Glutexo** [comment]
This is fixed. To some extent probably by #160.

I checked all the cases when the UUID is passed in the request and all are caught with _400 Bad Request_.

**Comment by Glutexo** [comment]
Created some pull requests to cover all the request UUID validation cases by tests. See #265.
